# -*- coding: utf-8 -*-
"""MODEL2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPuYMujt5TuSEUf2C1RAgtjBS9fdK5dx
"""

from  sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense

data=load_digits()
print(data)

x=data.data
y=data.target

print(x)

print(y)

y.size

from sklearn.preprocessing import StandardScaler,OneHotEncoder

scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)

x_scaled

from keras.utils import to_categorical
y_encoded=to_categorical(y)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y_encoded, test_size=0.2,random_state=42)
y_encoded.shape

x.shape

y.shape

x_test.shape

y_test.shape

model=Sequential()
model.add(Dense(32,input_shape=(x_train.shape[1],),activation='relu'))
model.add(Dense(3,activation='relu'))
model.add(Dense(10,activation='softmax'))

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

model.summary()

model.fit(x_train,y_train,epochs=30,batch_size=20,validation_data=(x_test,y_test))

print('loss',model.evaluate(x_test,y_test)[0])
print('accuracy',model.evaluate(x_test,y_test)[1])